# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapi/api.proto\x12\x08sent_vtt\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x11GetPatternRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x12GetPatternResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\x9a\x01\n\x15VTTSentPatternService\x12\x38\n\x05Hello\x12\x16.sent_vtt.HelloRequest\x1a\x17.sent_vtt.HelloResponse\x12G\n\nGetPattern\x12\x1b.sent_vtt.GetPatternRequest\x1a\x1c.sent_vtt.GetPatternResponseB\nZ\x08pkg/grpcb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLORESPONSE = DESCRIPTOR.message_types_by_name['HelloResponse']
_GETPATTERNREQUEST = DESCRIPTOR.message_types_by_name['GetPatternRequest']
_GETPATTERNRESPONSE = DESCRIPTOR.message_types_by_name['GetPatternResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'api.api_pb2'
  # @@protoc_insertion_point(class_scope:sent_vtt.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'api.api_pb2'
  # @@protoc_insertion_point(class_scope:sent_vtt.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

GetPatternRequest = _reflection.GeneratedProtocolMessageType('GetPatternRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPATTERNREQUEST,
  '__module__' : 'api.api_pb2'
  # @@protoc_insertion_point(class_scope:sent_vtt.GetPatternRequest)
  })
_sym_db.RegisterMessage(GetPatternRequest)

GetPatternResponse = _reflection.GeneratedProtocolMessageType('GetPatternResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPATTERNRESPONSE,
  '__module__' : 'api.api_pb2'
  # @@protoc_insertion_point(class_scope:sent_vtt.GetPatternResponse)
  })
_sym_db.RegisterMessage(GetPatternResponse)

_VTTSENTPATTERNSERVICE = DESCRIPTOR.services_by_name['VTTSentPatternService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010pkg/grpc'
  _HELLOREQUEST._serialized_start=27
  _HELLOREQUEST._serialized_end=55
  _HELLORESPONSE._serialized_start=57
  _HELLORESPONSE._serialized_end=89
  _GETPATTERNREQUEST._serialized_start=91
  _GETPATTERNREQUEST._serialized_end=124
  _GETPATTERNRESPONSE._serialized_start=126
  _GETPATTERNRESPONSE._serialized_end=160
  _VTTSENTPATTERNSERVICE._serialized_start=163
  _VTTSENTPATTERNSERVICE._serialized_end=317
# @@protoc_insertion_point(module_scope)
